### ISSUE TITLE
Supporting Scala 2.12 : Conflicting cross-version suffixes

### ISSUE THREAD

**Issue by honeyAndSw** [vert-x3/vertx-lang-scala#19]
Updates for Scala 2.12 break module dependencies, resolved with conflicting cross-version suffixes.

```
[error] Modules were resolved with conflicting cross-version suffixes in {file:/Users/vertx-microservices-workshop-scala/}common:
[error]    io.vertx:vertx-sql-common _2.12, <none>
[error]    io.vertx:vertx-jdbc-client _2.12, <none>
[error]    io.vertx:vertx-redis-client _2.12, <none>
[error]    io.vertx:vertx-web _2.12, <none>
[error]    io.vertx:vertx-service-discovery _2.12, <none>
```

It looks like sbt couldn't differentiate Scala library with _2.12 suffix and Java library without _2.12 suffix.

**Comment by codepitbull** [comment]
The current open PR will resolve this issue.
Cause of this issue is a name clash that causes sbt to fail.
Each module, vertx-web_2.12 in your case, also needs the corresponding java-version of the same module.
For sbt we now have vertx-web_2.12 and vertx-web visible. Sbt assumes that the later one needs a different Scala-version (<none>) and fails.
Our fix is to rename all the modules. Instead of vertx-web_2.12 you will now have vertx-web-scala_2.12.

I will close this issue as soon as the current PR has been merged and the new modules are available.

**Comment by codepitbull** [comment]
Fixed in current SNAPSHOTs.
