### ISSUE TITLE
[Web Client] Should not log error when using sendFuture

### ISSUE THREAD

**Issue by pabloromanelli** [vert-x3/vertx-lang-scala#44]
When making a request with the web client like this:
```scala
WebClient.create(vertx)
  .getAbs("https://...")
  .sendFuture()
  .recoverWith { ??? } // retry logic
```

If the server resets the connection, vertx logs the error:
```
ERROR i.vertx.core.net.impl.ConnectionBase - java.io.IOException: Connection reset by peer
```

Because I'm handling the error with retries, the error log is a bit misleading.

I found the actual log on ConnectionBase:
```java
  protected synchronized void handleException(Throwable t) {
    metrics().exceptionOccurred(metric(), remoteAddress(), t);
    if (exceptionHandler != null) {
      exceptionHandler.handle(t);
    } else {
      log.error(t);
    }
  }
```

I don't know if this is related to vertx-lang-scala (may be the initialization order of handlers) or if it is something with vertx-web in java.

Thank you

**Comment by codepitbull** [comment]
This is a collision between scala-Futures and the way Vert.x handles exceptions internally.
Not sure if there is a good way to avoid the logged exception.
I will check.

**Comment by codepitbull** [comment]
After some discussion on the mailinglist we came to the following decision:
We would recommend to disable logging for this case via the logging framework you are using as this isn't a bug. 
Vert.x supports two ways of handling errors, one via an exceptionHandler and the other via the returned Future. 
The problem is that there is no good way of knowing which one you picked so we have no way of telling if the handler has been intentionally left out and that's why we log these Exceptions.
Turning them off via the logging system is pretty reasonable.
