### ISSUE TITLE
Add Support For the Twirl Template Engine

### ISSUE THREAD

**Issue by mslinn** [vert-x3/vertx-lang-scala#59]
Many Scala users will have prior experience with [Twirl](https://github.com/playframework/twirl), and those with existing Twirl templates would be glad to know that those templates could be used on Vert.x with little or no changes.

**Comment by codepitbull** [comment]
Good recommendation. Adding this would definitely be nice.
I won't have time to do it in the forseeable future (current focus is on reactive streams and providing a small streaming library).

As always: PRs are very welcome!

**Comment by NikolajLeischner** [comment]
Not sure if it did in December 2017, but by now Twirl already works out of the box with Vert.x, see here: https://github.com/vert-x3/vertx-lang-scala/issues/69#issuecomment-507567743

If anything, the fact that Twirl can be used could be added to the documentation.

**Comment by oliver-brm** [comment]
As pointed out by Nikolaj, it works out of the box. That's because Twirl will take the template and compile it to Scala code, which you can _just use_ from your Vert.x/Scala code. For other template engines, a mechanism is required in Vert.x, which provides some kind of context to the template engine, so it would be able to resolve all the variables in the template. Twirl does not need that. You'd just run `html.MyTemplate.apply(someContext)`.
