### ISSUE TITLE
stopFuture() not triggered

### ISSUE THREAD

**Issue by k33g** [vert-x3/vertx-lang-scala#61]
👋 Hello 🌍 
This is my baby steps with Scala and Vert.x

I'm trying to create a microservice sample scala project "from scratch" with the Redis backend
(you can read the code here https://github.com/botsgarden/b.nlp/blob/master/src/main/scala/brain/BeeNlp.scala)

Almost all is ok:

I deploy the ScalaVerticle with a companion object:

```scala
object BeeNlp extends App {

  val vertx = Vertx.vertx
  
  // do some stuff, initialize discovery backend, etc...

  vertx
    .deployVerticleFuture(ScalaVerticle.nameForVerticle[brain.BeeNlp])
    .onComplete {
      case Success(verticleId) => println(s"Successfully deployed verticle: $verticleId")
      case Failure(error) => println(s"Failed to deploy verticle: $error")
    }

}
```

this is my verticle:

```scala
class BeeNlp extends ScalaVerticle {

  override def startFuture(): Future[_] = {
    
    val server = vertx.createHttpServer()
    val router = Router.router(vertx)
    val httpPort = sys.env.getOrElse("PORT", "8080").toInt

    // publish the microservice record
    BeeNlp.discovery.publishFuture(BeeNlp.record).onComplete{
      case Success(result) => println(s"😃 publication OK")
      case Failure(cause) => println(s"😡 publication KO: $cause")
    }
    
    router.route().handler(BodyHandler.create)

    router.get("/hey").handler(context => 
      context
        .response
        .putHeader("content-type", "application/json;charset=UTF-8")
        .end(new JsonObject().put("message", "👋 hey!").encodePrettily)                            
    )

    router.route("/*").handler(StaticHandler.create)

    println(s"🌍 Listening on $httpPort  - Enjoy 😄")
    server.requestHandler(router.accept _).listenFuture(httpPort)
  }

```

I would like to unpublish the record verticle from the Redis backend when I quit.
With **Java** I do like that:

```java
public void stop(Future<Void> stopFuture) {
  System.out.println("Unregistration process is started ("+record.getRegistration()+")...");

  discovery.unpublish(record.getRegistration(), asyncResult -> {
    if(asyncResult.succeeded()) {
      System.out.println("👋 bye bye " + record.getRegistration());
    } else {
      System.out.println("😡 Not able to unpublish the microservice: " + asyncResult.cause().getMessage());
      //asyncResult.cause().printStackTrace();
    }
    stopFuture.complete();
  });
}
```

and `stop` method is triggered when I quit
but I can't do the same thing with Scala :

I try something like that with override `def stopFuture(): Future[_] = {...}`
but I can't trigger anything when the microservice exits (again: this is my baby steps 😉)

```scala
override def stopFuture(): Future[_] = {
  var unpublishRecordFuture = BeeSlack.discovery.unpublishFuture(BeeSlack.record.getRegistration)
  
  unpublishRecordFuture.onComplete {
    case Success(result) => {
      println(s"😃 removing publication OK")
      Future.successful(())
    }
    case Failure(cause) => {
      println(s"😡 removing publication KO: $cause")
      Future.failed(new Throwable())
    }
  }
  unpublishRecordFuture
}
```

It's probably easy, but I don't find a solution.

Does anybody know an example about this or has an idea?

Regards
Philippe

**Comment by codepitbull** [comment]
I finally got some time yesterday to look at the issue.
First: It's not a Vert.x-Bug.
The problem lies within the way you use the Vertx-instance.
But first about the solution, add the following lines to the end BeeSlack (the part that extends App):

```
Runtime.getRuntime.addShutdownHook(new Thread() {
  override def run(): Unit = {
    Await.result(vertx.closeFuture(), 1000 millis)
  }
})
```

**Now for the reason:**
You are using a Vertx-instance you created yourself, those don't register a shutdown-hook (something io.vertx.core.Launcher takes ccare of) and have no chance of executing the stop-code if the JVM exits.
we provide a Vertx-quickstart that does all the required bootstrapping for you to avoid this (run sbt new vert-x3/vertx-scala.g8 to get fully configured project).

**Why did it run with Java?**
Well, you most likely used one of the provided startes (Maven/Gradle/...) or something else that didn't use Vertx directly but instead relied on the Launcher.

**Some further comments on your code:**
Vert.x is all about isolation so please don't share anything by reference. Service-discovery/registration should be done inside a verticle to avoid contention and/or threading problems :)

**Comment by k33g** [comment]
@codepitbull thank you very much for these explanations 🙂
