### ISSUE TITLE
Benchmarking Vert.x Scala vs Java?

### ISSUE THREAD

**Issue by kajmagnus** [vert-x3/vertx-lang-scala#69]
There's Web Framework Benchmarks at `techempower.com`:

https://www.techempower.com/benchmarks/#section=data-r16
https://news.ycombinator.com/item?id=17254152

and Vert.x is super fast :- )

What about constructing and submitting benchmarks for Vert.x + Scala? I think it'd be really interesting to see how fast Scala is currently, and ... maybe if it's slower than Java, that indicates there's lots of room for improvement?

https://groups.google.com/forum/#!topic/framework-benchmarks/6JwoofFRrOU

(I'm thinking someone will suggest that I do this myself. That's a good idea ... and I work to long weeks already, and feel I'm a bit short of time. Otherwise yes it'd been interesting to do that :- )  now I'm just hoping that someone else will think this would be an interesting thing to do, & do all the work)

Maybe if Vert.x + Scala turns out to be 10 x faster than Play Framework 2 + Scala — that's something that can make people even more interested in Vert.x (?).

**Comment by vietj** [comment]
@kajmagnus are you interested in contributing this in the community ?

**Comment by codepitbull** [comment]
Benchmarking the different language implementation sounds like a great idea.
It's something I have been thinking about for quite a while but I am running into the same problem: time.
I'd be happily supporting such an effort nbut won't be able to pull it off alone since I maintiain vertx-lang-scala in my freetime.

**Comment by codepitbull** [comment]
I will keep this issue open as a reminder and a possible entry point for others to get started on this topic.

**Comment by kajmagnus** [comment]
codepitbull: Ok :- )

@vietj  I'm too short of time (because of working in a small startup), otherwise seems like an interesting thing to do

**Comment by codepitbull** [comment]
I will be revisiting this for Vert.x 4.

**Comment by NikolajLeischner** [comment]
FYI, I took the liberty of porting the Java version of the Techempower Vert.x benchmark to Scala.

https://www.techempower.com/benchmarks/#section=test&runid=668c43a2-5caa-4075-91ab-8ee9537b5dec
https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Scala/vertx-web-scala

The code for the database queries is quite close to the Java version since I didn't take the time to wrap the reactive-pg-client API to make it more idiomatic for Scala.

Also, I used Twirl for HTML templating, which might explain the lower performance in the 'Fortunes' benchmark, compared to 'vertx-postgress'.

Feel free to improve on this :)

**Comment by codepitbull** [comment]
You just became my personal hero :) Thanks for the effort!

**Comment by kajmagnus** [comment]
Wow this is amazing: https://www.techempower.com/benchmarks/#section=test&runid=668c43a2-5caa-4075-91ab-8ee9537b5dec&hw=ph&test=query  — vertx-web-scala is number 4, in the Multiple Queries test (which in my case is the one closest to "reality" I think ... had I been using Vert.x not Play Fmw).

Thanks @NikolajLeischner  for porting.

**Comment by NikolajLeischner** [comment]
@kajmagnus By that I mean how the database access works code-wise. It uses callbacks and actual while-loops, which isn't how one wants Scala code to look like normally :)

**Comment by codepitbull** [comment]
This is great and also shows areas where vertx-scala should be improved.
The pgClient is something I haven't touched so far because ... well, I simply didn't think about it.
There is a new version of vertx-scala in the works (https://github.com/vert-x3/vertx-lang-scala/tree/4.0) which is completely based on extension methods.
This should bring down the allocation rate a lot.
I should tackle the reactiverse stuff and provide the needed extensions.
Thanks again, great work :)

**Comment by vietj** [comment]
in Vert.x 3.8 and 4.0 the PG client is part of the stack as SQL client (and provides support for MySQL as well).

**Comment by oliver-brm** [comment]
I think it's time to close this issue. There is a benchmark app, as mentioned, in the [TechEmpower/FrameworkBenchmarks](https://github.com/TechEmpower/FrameworkBenchmarks/tree/270785334606891acdc847bf62ed2a133b2cccd9/frameworks/Scala/vertx-web-scala) repository. It's currently using Vert.x 3.9, Scala 2.12 and is running on JVM 17. We should upgrade it to the latest Vert.x/Scala version. But that's not in scope for this issue anymore. Thanks for the good work!
